
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 19 21:20:35 ART 2015
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DECIMAL = 12;
  public static final int INTEGRAL = 11;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int RBRACKET = 9;
  public static final int ID = 10;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 4;
  public static final int LBRACKET = 8;
  public static final int LPAREN = 6;
}

