
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 26 00:05:48 ART 2015
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LINE_TERMINATOR = 80;
  public static final int TUPLE_FUNC = 72;
  public static final int TIMES = 6;
  public static final int STRING_FUNC = 76;
  public static final int DIV_INT = 9;
  public static final int EXP = 7;
  public static final int SPLIT_FUNC = 59;
  public static final int REPLACE_FUNC = 60;
  public static final int COMMA = 33;
  public static final int HAS_KEY_FUNC = 51;
  public static final int RBRACE = 38;
  public static final int RPAREN = 36;
  public static final int PRINT_FUNC = 68;
  public static final int INTEGER = 2;
  public static final int LBRACE = 37;
  public static final int LPAREN = 35;
  public static final int LIST_FUNC = 73;
  public static final int FALSE = 21;
  public static final int NOT = 24;
  public static final int DEF = 49;
  public static final int XOR_BIT = 13;
  public static final int FLOAT_FUNC = 70;
  public static final int FLOAT = 3;
  public static final int EXTEND_FUNC = 63;
  public static final int RAW_INPUT_FUNC = 67;
  public static final int DICT_FUNC = 74;
  public static final int MOD = 10;
  public static final int TRUE = 20;
  public static final int TAB = 19;
  public static final int PLUS = 4;
  public static final int WHILE = 44;
  public static final int ASSIGN = 41;
  public static final int INT_FUNC = 69;
  public static final int NONE = 77;
  public static final int VALUES_FUNC = 55;
  public static final int FOR = 47;
  public static final int GREATER = 28;
  public static final int ESCAPE = 18;
  public static final int DIV = 8;
  public static final int RETURN = 50;
  public static final int APPEND_FUNC = 62;
  public static final int INDEX_FUNC = 64;
  public static final int ELSE = 43;
  public static final int POINT = 31;
  public static final int BREAK = 45;
  public static final int COUNT_FUNC = 56;
  public static final int EOF = 0;
  public static final int SEMICOLON = 32;
  public static final int ITEMS_FUNC = 52;
  public static final int TYPE_FUNC = 78;
  public static final int NOT_BIT = 14;
  public static final int KEYS_FUNC = 53;
  public static final int MINUS = 5;
  public static final int LENGTH_FUNC = 61;
  public static final int IN = 48;
  public static final int OR = 23;
  public static final int error = 1;
  public static final int STR_FUNC = 71;
  public static final int CONTINUE = 46;
  public static final int IF = 42;
  public static final int ID = 79;
  public static final int GREATER_EQUAL = 30;
  public static final int COLON = 34;
  public static final int FIND_FUNC = 57;
  public static final int LESS_EQUAL = 29;
  public static final int RBRACKET = 40;
  public static final int LONG_FUNC = 75;
  public static final int JOIN_FUNC = 58;
  public static final int RSHIFT = 16;
  public static final int STRING = 17;
  public static final int LESS = 27;
  public static final int SIZE_FUNC = 66;
  public static final int AND_BIT = 11;
  public static final int AND = 22;
  public static final int INSERT_FUNC = 65;
  public static final int LBRACKET = 39;
  public static final int OR_BIT = 12;
  public static final int LSHIFT = 15;
  public static final int DISTINCT = 26;
  public static final int EQUALS = 25;
  public static final int POP_FUNC = 54;
}

